# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='empty text'),
            preserve_default=False,
        ),
    ]
